# Generated by Django 3.2.8 on 2023-01-30 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=8)),
                ('id_number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('job_number', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('id_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=4)),
                ('position', models.CharField(max_length=12)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeesAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_date', models.CharField(default='2023-01-30', max_length=20)),
                ('go_time', models.DateTimeField(auto_now_add=True)),
                ('off_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10)),
                ('purchase_time', models.DateTimeField()),
                ('purchase_business', models.CharField(max_length=20)),
                ('usage', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ViolationInformation',
            fields=[
                ('violation_id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('violation_type', models.CharField(max_length=12)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.equipment')),
                ('job_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.employees')),
            ],
        ),
        migrations.CreateModel(
            name='PatrolInspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.CharField(default='2023-01-30', max_length=20)),
                ('violations_number', models.IntegerField()),
                ('manage_name', models.CharField(max_length=10)),
                ('video_url', models.CharField(max_length=100)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.equipment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(check=models.Q(('type', '无人机'), ('type', '监控'), _connector='OR'), name='check_type'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(check=models.Q(('usage', '极好'), ('usage', '良好'), ('usage', '不佳'), ('usage', '报废'), _connector='OR'), name='check_usage'),
        ),
        migrations.AddField(
            model_name='employeesattendance',
            name='job_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.employees'),
        ),
        migrations.AddConstraint(
            model_name='employees',
            constraint=models.UniqueConstraint(fields=('password', 'id_number'), name='unique_password_id_number'),
        ),
        migrations.AddConstraint(
            model_name='administrator',
            constraint=models.UniqueConstraint(fields=('password',), name='unique_password'),
        ),
        migrations.AddConstraint(
            model_name='patrolinspectionlog',
            constraint=models.UniqueConstraint(fields=('record_date', 'equipment_id'), name='union_primary_key_record_date_equipment_id'),
        ),
        migrations.AddConstraint(
            model_name='employeesattendance',
            constraint=models.UniqueConstraint(fields=('job_number', 'day_date'), name='union_primary_key_password_id_number'),
        ),
    ]
